# Based on https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: CD
on:
  push:
    branches:
      - main
jobs:
  cd:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup 🏗
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install ⚙️
        run: npm ci
      - name: Build 🛠
        run: npm run build:ci
      - name: Test 📋
        run: npm run test:ci
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: trishi-ri/testcicd
          branch: gh-pages
          folder: dist/testcicd
          target-folder: testcicd
          token: ${{ secrets.GH_TOKEN }}
