# Based on https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v2
      - name: Setup 🏗
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install ⚙️
        run: npm ci
      - name: Build 🛠
        run: npm run build:ci
      - name: Test 📋
        run: npm run test:ci
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: trishi-ri/trishi-ri.github.io
          branch: gh-pages
          folder: dist/testcicd
          target-folder: testcicd
          token: ${{ secrets.GH_TOKEN }}
